### ISSUE TITLE
[auth][error] UnknownAction: Cannot parse action at /session .

### ISSUE THREAD

**Issue by Undertone0809** [vercel/nextjs-postgres-nextauth-tailwindcss-template#45]
I clone the project and run `pnpm i` & `pnpm dev` show the following error. I try to find the solution but still failed.

Win11 system.
Node 20/ Node 22 both fail

![image](https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/assets/72488598/69211428-913e-4a67-8f9f-8c753c8bd79d)

```
(base) PS D:\Projects\githubhub\nextjs-pg-nextauth-demo> pnpm dev

> @ dev D:\Projects\githubhub\nextjs-pg-nextauth-demo
> next dev --turbo

 ⚠ Port 3000 is in use, trying 3001 instead.
  ▲ Next.js 14.2.1 (turbo)
  - Local:        http://localhost:3001
  - Environments: .env

 ✓ Starting...
 ✓ Compiled in 240ms
 ✓ Ready in 2.1s
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
[auth][error] UnknownAction: Cannot parse action at /session .Read more at https://errors.authjs.dev#unknownaction
    at parseActionAndProviderId (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:839:27)
    at toInternalRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:784:40)
    at Auth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\9b3ba_@auth_core_83ff25._.js:4866:270)
    at getSession (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3146:236)
    at handleAuth (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3258:35)
    at Object.handler (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\node_modules__pnpm_10a95f._.js:3229:20)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5086:31
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:4628:24)
    at D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\server\edge\chunks\ssr\_bdf703._.js:5073:355
 ○ Compiling / ...
 ✓ Compiled / in 1931ms
 ⨯ ModuleBuildError: ./app/globals.css
Error evaluating Node.js code
Error: Failed to load external module D:\Projects\githubhub\nextjs-pg-nextauth-demo/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\chunks\[output]__next_transform_ad1f0f.js:1345:15]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (postcss.config.js_.loader.mjs:3:13) [D:\Projects\githubhub\nextjs-pg-nextauth-demo\.next\chunks\_0b8f1c._.js:11:13]


    at processIssues (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\turbopack-utils.js:229:15)
    at handleRouteType (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\turbopack-utils.js:386:17)
    at async Object.ensurePage (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\hot-reloader-turbopack.js:644:17)
    at async DevBundlerService.ensurePage (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:551:9)
    at async Object.ensure (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:169:17)      
    at async DevRouteMatcherManager.matchAll (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:228:31)
    at async DevServer.handleRequestImpl (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:811:17)
    at async D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:353:24)        
    at async requestHandlerImpl (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:377:13)   
    at async Server.requestListener (D:\Projects\githubhub\nextjs-pg-nextauth-demo\node_modules\.pnpm\next@14.2.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:141:13)
 ○ Compiling /_error ...
 ✓ Compiled /_error in 502ms
 GET / 500 in 2717ms
 GET / 500 in 2711ms
 ✓ Compiled /favicon.ico in 56ms
 GET /favicon.ico 500 in 89ms

```

**Comment by mnavaltaequitydine** [comment]
Remove the --turbo in the dev, it seems it is current experimental.

**Comment by leerob** [comment]
Fixed https://github.com/vercel/nextjs-postgres-nextauth-tailwindcss-template/commit/3b3e7ebec6ae6464f29ea27d1381e4407cc01ef8
